title: Florida Trials Association
description: A club dedicated to the family-friendly sport of observed motorcycle trials
baseurl: "FloridaTrialsAssociation"
url: "https://justin-vanwinkle.github.io/FloridaTrialsAssociation"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
  sass_dir: _sass

# Navigation
navigation:
  - title: Home
    url: /FloridaTrialsAssociation/
  - title: Event Schedule
    url: /FloridaTrialsAssociation/events/
  - title: Forms and Rules
    url: /FloridaTrialsAssociation/forms-rules/
  - title: Photos
    url: /FloridaTrialsAssociation/photos/
  - title: Links and Bikes
    url: /FloridaTrialsAssociation/links/
  - title: About Us
    url: /FloridaTrialsAssociation/about/
  - title: Results
    url: /FloridaTrialsAssociation/results/
  - title: What is Moto-Trials?
    url: /FloridaTrialsAssociation/moto-trials/

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - postcss.config.js
  - Gemfile
  - Gemfile.lock